//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.04.02 at 03:27:54 PST 
//


package simkit.xsd.bindings.assembly;


/**
 * Java content class for Parameters element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/rmgold/CVS/Simkit/simkit/xsd/assembly/assembly.xsd line 3)
 * <p>
 * <pre>
 * &lt;element name="Parameters" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 * </pre>
 * 
 */
public interface Parameters
    extends javax.xml.bind.Element, simkit.xsd.bindings.assembly.AnyType
{


}
