//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.24 at 03:22:43 PST 
//


package simkit.xsd.bindings.impl;

public class EventImpl
    extends simkit.xsd.bindings.impl.EventTypeImpl
    implements simkit.xsd.bindings.Event, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, simkit.xsd.bindings.impl.runtime.UnmarshallableObject, simkit.xsd.bindings.impl.runtime.XMLSerializable, simkit.xsd.bindings.impl.runtime.ValidatableObject
{

    public final static java.lang.Class version = (simkit.xsd.bindings.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (simkit.xsd.bindings.Event.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "Event";
    }

    public simkit.xsd.bindings.impl.runtime.UnmarshallingEventHandler createUnmarshaller(simkit.xsd.bindings.impl.runtime.UnmarshallingContext context) {
        return new simkit.xsd.bindings.impl.EventImpl.Unmarshaller(context);
    }

    public void serializeBody(simkit.xsd.bindings.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "Event");
        super.serializeURIs(context);
        context.endNamespaceDecls();
        super.serializeAttributes(context);
        context.endAttributes();
        super.serializeBody(context);
        context.endElement();
    }

    public void serializeAttributes(simkit.xsd.bindings.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(simkit.xsd.bindings.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (simkit.xsd.bindings.Event.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilon"
+"Reducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xp\n{0\u00e2p"
+"p\u0000sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~"
+"\u0000\u0004\n{0\u00d7ppsq\u0000~\u0000\u0007\t\u0005\u00e0\u00d6ppsq\u0000~\u0000\u0007\u0005\u00f2yappsq\u0000~\u0000\u0007\u0005\u0092\u001c:ppsq\u0000~\u0000\u0007\u0004\u00e1{bppsq\u0000~"
+"\u0000\u0007\u0003\u00ccF\u008cppsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\b\u0001\u0082"
+"s\u0018ppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.s"
+"un.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000\u0004\u0001\u0082s\rsr\u0000\u0011j"
+"ava.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u0000\u0001\u0082s\nq\u0000~\u0000\u0015p\u0000sq\u0000~"
+"\u0000\u0007\u0001\u0082r\u00ffppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLo"
+"rg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom/su"
+"n/msv/util/StringPair;xq\u0000~\u0000\u0004\u0000\u0005\u009aDppsr\u0000#com.sun.msv.datatype.x"
+"sd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.data"
+"type.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatyp"
+"e.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XS"
+"DatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L"
+"\u0000\btypeNameq\u0000~\u0000 L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/Whi"
+"teSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006str"
+"ingsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetExpre"
+"ssion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0"
+"t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000 L\u0000\fnamespaceURIq\u0000~\u0000 xpq\u0000~\u0000$q\u0000~\u0000#s"
+"q\u0000~\u0000\u000f\u0001|\u00d8\u00b6ppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000"
+"\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004\u0001|\u00d8\u00abq\u0000~\u0000\u0015psq\u0000~\u0000\u0018\u0000\n\u00b4Tppsr\u0000\"co"
+"m.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001dq\u0000~\u0000#t\u0000\u0005QNa"
+"mesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000&q\u0000~\u0000)sq\u0000~\u0000*q\u0000~\u00002q\u0000~\u0000#sr\u0000#com.sun.msv.grammar"
+".SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000 L\u0000\fnamespaceURIq"
+"\u0000~\u0000 xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)"
+"http://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv.gra"
+"mmar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\tsq\u0000~\u0000\u0014"
+"\u0001psq\u0000~\u00006t\u0000\u0007Commentt\u0000\u0000q\u0000~\u0000<sq\u0000~\u0000\u000f\u0002I\u00d3oppsq\u0000~\u0000\u0011\u0002I\u00d3dq\u0000~\u0000\u0015psq\u0000~\u0000\u000f"
+"\u0002I\u00d3aq\u0000~\u0000\u0015psq\u0000~\u0000\u0000\u00000.\u0089q\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u000f\u00000.~ppsq\u0000~\u0000\u0011\u00000.sq\u0000~\u0000\u0015psq\u0000~\u0000"
+"-\u00000.pq\u0000~\u0000\u0015psr\u00002com.sun.msv.grammar.Expression$AnyStringExpre"
+"ssion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\bq\u0000~\u0000=psr\u0000 com.sun.msv.grammar.AnyN"
+"ameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00007q\u0000~\u0000<sq\u0000~\u00006t\u0000\u001csimkit.xsd.bindings.A"
+"rgumentt\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\u0000\u0002"
+"\u0019\u00a4\u00d6q\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0007\u0002\u0019\u00a4\u00cbppsq\u0000~\u0000\u0000\u00000.\u0089pp\u0000sq\u0000~\u0000\u000f\u00000.~ppsq\u0000~\u0000\u0011\u00000.sq\u0000~"
+"\u0000\u0015psq\u0000~\u0000-\u00000.pq\u0000~\u0000\u0015pq\u0000~\u0000Iq\u0000~\u0000Kq\u0000~\u0000<sq\u0000~\u00006t\u0000 simkit.xsd.bindin"
+"gs.ArgumentTypeq\u0000~\u0000Nsq\u0000~\u0000\u000f\u0001\u00e9v=ppsq\u0000~\u0000-\u0001\u00e9v2q\u0000~\u0000\u0015pq\u0000~\u0000/sq\u0000~\u00006q"
+"\u0000~\u00009q\u0000~\u0000:q\u0000~\u0000<sq\u0000~\u00006t\u0000\bArgumentq\u0000~\u0000@q\u0000~\u0000<sq\u0000~\u0000\u000f\u0001\u00154\u00d1ppsq\u0000~\u0000\u0011\u0001"
+"\u00154\u00c6q\u0000~\u0000\u0015psq\u0000~\u0000\u000f\u0001\u00154\u00c3q\u0000~\u0000\u0015psq\u0000~\u0000\u0000\u00000.\u0089q\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u000f\u00000.~ppsq\u0000~\u0000\u0011"
+"\u00000.sq\u0000~\u0000\u0015psq\u0000~\u0000-\u00000.pq\u0000~\u0000\u0015pq\u0000~\u0000Iq\u0000~\u0000Kq\u0000~\u0000<sq\u0000~\u00006t\u0000!simkit.xsd"
+".bindings.LocalVariableq\u0000~\u0000Nsq\u0000~\u0000\u0000\u0000\u00e5\u00068q\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0007\u0000\u00e5\u0006-ppsq\u0000"
+"~\u0000\u0000\u00000.\u0089pp\u0000sq\u0000~\u0000\u000f\u00000.~ppsq\u0000~\u0000\u0011\u00000.sq\u0000~\u0000\u0015psq\u0000~\u0000-\u00000.pq\u0000~\u0000\u0015pq\u0000~\u0000Iq"
+"\u0000~\u0000Kq\u0000~\u0000<sq\u0000~\u00006t\u0000%simkit.xsd.bindings.LocalVariableTypeq\u0000~\u0000N"
+"sq\u0000~\u0000\u000f\u0000\u00b4\u00d7\u009fppsq\u0000~\u0000-\u0000\u00b4\u00d7\u0094q\u0000~\u0000\u0015pq\u0000~\u0000/sq\u0000~\u00006q\u0000~\u00009q\u0000~\u0000:q\u0000~\u0000<sq\u0000~\u00006"
+"t\u0000\rLocalVariableq\u0000~\u0000@q\u0000~\u0000<sq\u0000~\u0000\u000f\u0000\u00b0\u00a0\u00d3ppsq\u0000~\u0000\u0011\u0000\u00b0\u00a0\u00c8q\u0000~\u0000\u0015psq\u0000~\u0000\u000f"
+"\u0000\u00b0\u00a0\u00c5q\u0000~\u0000\u0015psq\u0000~\u0000\u0000\u00000.\u0089q\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u000f\u00000.~ppsq\u0000~\u0000\u0011\u00000.sq\u0000~\u0000\u0015psq\u0000~\u0000"
+"-\u00000.pq\u0000~\u0000\u0015pq\u0000~\u0000Iq\u0000~\u0000Kq\u0000~\u0000<sq\u0000~\u00006t\u0000#simkit.xsd.bindings.State"
+"Transitionq\u0000~\u0000Nsq\u0000~\u0000\u0000\u0000\u0080r:q\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0007\u0000\u0080r/ppsq\u0000~\u0000\u0000\u00000.\u0089pp\u0000sq\u0000"
+"~\u0000\u000f\u00000.~ppsq\u0000~\u0000\u0011\u00000.sq\u0000~\u0000\u0015psq\u0000~\u0000-\u00000.pq\u0000~\u0000\u0015pq\u0000~\u0000Iq\u0000~\u0000Kq\u0000~\u0000<sq\u0000~"
+"\u00006t\u0000\'simkit.xsd.bindings.StateTransitionTypeq\u0000~\u0000Nsq\u0000~\u0000\u000f\u0000PC\u00a1p"
+"psq\u0000~\u0000-\u0000PC\u0096q\u0000~\u0000\u0015pq\u0000~\u0000/sq\u0000~\u00006q\u0000~\u00009q\u0000~\u0000:q\u0000~\u0000<sq\u0000~\u00006t\u0000\u000fStateTra"
+"nsitionq\u0000~\u0000@q\u0000~\u0000<sq\u0000~\u0000\u000f\u0000`]\"ppsq\u0000~\u0000\u0011\u0000`]\u0017q\u0000~\u0000\u0015psq\u0000~\u0000\u000f\u0000`]\u0014q\u0000~\u0000\u0015"
+"psq\u0000~\u0000\u0000\u00000.\u0089q\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u000f\u00000.~ppsq\u0000~\u0000\u0011\u00000.sq\u0000~\u0000\u0015psq\u0000~\u0000-\u00000.pq\u0000~\u0000"
+"\u0015pq\u0000~\u0000Iq\u0000~\u0000Kq\u0000~\u0000<sq\u0000~\u00006t\u0000\u001csimkit.xsd.bindings.Scheduleq\u0000~\u0000Ns"
+"q\u0000~\u0000\u0000\u00000.\u0089q\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u000f\u00000.~ppsq\u0000~\u0000\u0011\u00000.sq\u0000~\u0000\u0015psq\u0000~\u0000-\u00000.pq\u0000~\u0000\u0015p"
+"q\u0000~\u0000Iq\u0000~\u0000Kq\u0000~\u0000<sq\u0000~\u00006t\u0000\u001asimkit.xsd.bindings.Cancelq\u0000~\u0000Nq\u0000~\u0000<"
+"sq\u0000~\u0000-\u0003\u0013gpppsq\u0000~\u0000\u0018\u0001\u00fam(ppsr\u0000\u001fcom.sun.msv.datatype.xsd.IDType\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.NcnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xr\u0000\"com.sun.msv.datatype.xsd.TokenType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001cq\u0000~\u0000#"
+"t\u0000\u0002IDq\u0000~\u00004\u0000q\u0000~\u0000)sq\u0000~\u0000*q\u0000~\u0000\u009dq\u0000~\u0000#sq\u0000~\u00006t\u0000\u0004nameq\u0000~\u0000@sq\u0000~\u0000\u000f\u0001uO\u00fc"
+"ppsq\u0000~\u0000-\u0001uO\u00f1q\u0000~\u0000\u0015pq\u0000~\u0000/sq\u0000~\u00006q\u0000~\u00009q\u0000~\u0000:q\u0000~\u0000<sq\u0000~\u00006t\u0000\u0005Eventq\u0000"
+"~\u0000@sr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTa"
+"blet\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-c"
+"om.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005co"
+"untI\u0000\tthresholdL\u0000\u0006parentq\u0000~\u0000\u00a7[\u0000\u0005tablet\u0000![Lcom/sun/msv/gramma"
+"r/Expression;xp\u0000\u0000\u0000-\u0000\u0000\u00009pur\u0000![Lcom.sun.msv.grammar.Expression"
+";\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfpppppppq\u0000~\u0000Fq\u0000~\u0000Sq\u0000~\u0000aq\u0000~\u0000iq\u0000~\u0000wq\u0000~\u0000\u007fq\u0000~\u0000\u008d"
+"q\u0000~\u0000^q\u0000~\u0000\u0093pq\u0000~\u0000]q\u0000~\u0000Eq\u0000~\u0000Rq\u0000~\u0000`q\u0000~\u0000hq\u0000~\u0000vq\u0000~\u0000~q\u0000~\u0000\u008cq\u0000~\u0000\u0092q\u0000~\u0000"
+"\u00a1pq\u0000~\u0000\\pppppppppppppq\u0000~\u0000,ppppppppppq\u0000~\u0000\u0083ppppppq\u0000~\u0000\u008appq\u0000~\u0000\u0089pp"
+"pppq\u0000~\u0000Wppppq\u0000~\u0000\u0088pq\u0000~\u0000\nppppppppppq\u0000~\u0000|pppppppppppppppq\u0000~\u0000Pq\u0000"
+"~\u0000\tq\u0000~\u0000\fpppppppppq\u0000~\u0000\u000epq\u0000~\u0000\u0017pppppppppppq\u0000~\u0000mq\u0000~\u0000tq\u0000~\u0000\u0013q\u0000~\u0000sp"
+"ppppppppq\u0000~\u0000\u0010q\u0000~\u0000rpq\u0000~\u0000Cppq\u0000~\u0000Bq\u0000~\u0000\rpppppppppq\u0000~\u0000Apppq\u0000~\u0000fpp"
+"ppppppppppppppppppq\u0000~\u0000\u000bpppppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends simkit.xsd.bindings.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(simkit.xsd.bindings.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(simkit.xsd.bindings.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return simkit.xsd.bindings.impl.EventImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        attIdx = context.getAttribute("", "name");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        if (("Event" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        attIdx = context.getAttribute("", "name");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        if (("Event" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        if (("name" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((simkit.xsd.bindings.impl.EventTypeImpl)simkit.xsd.bindings.impl.EventImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        attIdx = context.getAttribute("", "name");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  1 :
                            attIdx = context.getAttribute("", "name");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
