//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.25 at 11:41:55 PST 
//


package simkit.xsd.bindings.impl;

public class SimkitModuleImpl
    extends simkit.xsd.bindings.impl.SimkitModuleTypeImpl
    implements simkit.xsd.bindings.SimkitModule, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, simkit.xsd.bindings.impl.runtime.UnmarshallableObject, simkit.xsd.bindings.impl.runtime.XMLSerializable, simkit.xsd.bindings.impl.runtime.ValidatableObject
{

    public final static java.lang.Class version = (simkit.xsd.bindings.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (simkit.xsd.bindings.SimkitModule.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "SimkitModule";
    }

    public simkit.xsd.bindings.impl.runtime.UnmarshallingEventHandler createUnmarshaller(simkit.xsd.bindings.impl.runtime.UnmarshallingContext context) {
        return new simkit.xsd.bindings.impl.SimkitModuleImpl.Unmarshaller(context);
    }

    public void serializeBody(simkit.xsd.bindings.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "SimkitModule");
        super.serializeURIs(context);
        context.endNamespaceDecls();
        super.serializeAttributes(context);
        context.endAttributes();
        super.serializeBody(context);
        context.endElement();
    }

    public void serializeAttributes(simkit.xsd.bindings.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(simkit.xsd.bindings.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (simkit.xsd.bindings.SimkitModule.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilon"
+"Reducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xp\u001c\u00c7\u00f6\u00f5p"
+"p\u0000sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~"
+"\u0000\u0004\u001c\u00c7\u00f6\u00eappsq\u0000~\u0000\u0007\u001a\u001a\u0085\u00a3ppsq\u0000~\u0000\u0007\u0016\u00a1\u00e4 ppsq\u0000~\u0000\u0007\u0014\u0007toppsq\u0000~\u0000\u0007\r\u00ba[sppsq\u0000~"
+"\u0000\u0007\u0007\u00ed\u009ccppsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\b\u0002\u0089"
+"\u00e0\u00d2ppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.s"
+"un.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000\u0004\u0002\u0089\u00e0\u00c7sr\u0000\u0011j"
+"ava.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u0000\u0002\u0089\u00e0\u00c4q\u0000~\u0000\u0015p\u0000sq\u0000~"
+"\u0000\u0007\u0002\u0089\u00e0\u00b9ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLo"
+"rg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom/su"
+"n/msv/util/StringPair;xq\u0000~\u0000\u0004\u0000t\u007f\u00b2ppsr\u0000#com.sun.msv.datatype.x"
+"sd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.data"
+"type.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatyp"
+"e.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XS"
+"DatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L"
+"\u0000\btypeNameq\u0000~\u0000 L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/Whi"
+"teSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006str"
+"ingsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetExpre"
+"ssion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0"
+"t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000 L\u0000\fnamespaceURIq\u0000~\u0000 xpq\u0000~\u0000$q\u0000~\u0000#s"
+"q\u0000~\u0000\u000f\u0002\u0015a\u0002ppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000"
+"\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004\u0002\u0015`\u00f7q\u0000~\u0000\u0015psq\u0000~\u0000\u0018\u0001\u009du\u00feppsr\u0000\"co"
+"m.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001dq\u0000~\u0000#t\u0000\u0005QNa"
+"mesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000&q\u0000~\u0000)sq\u0000~\u0000*q\u0000~\u00002q\u0000~\u0000#sr\u0000#com.sun.msv.grammar"
+".SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000 L\u0000\fnamespaceURIq"
+"\u0000~\u0000 xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)"
+"http://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv.gra"
+"mmar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\tsq\u0000~\u0000\u0014"
+"\u0001psq\u0000~\u00006t\u0000\u0007Commentt\u0000\u0000q\u0000~\u0000<sq\u0000~\u0000\u000f\u0005c\u00bb\u008cppsq\u0000~\u0000\u0011\u0005c\u00bb\u0081q\u0000~\u0000\u0015psq\u0000~\u0000\u000f"
+"\u0005c\u00bb~q\u0000~\u0000\u0015psq\u0000~\u0000\u0000\u0001\u0095\u00dd}q\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u000f\u0001\u0095\u00ddrppsq\u0000~\u0000\u0011\u0001\u0095\u00ddgq\u0000~\u0000\u0015psq\u0000~\u0000"
+"-\u0001\u0095\u00dddq\u0000~\u0000\u0015psr\u00002com.sun.msv.grammar.Expression$AnyStringExpre"
+"ssion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\bq\u0000~\u0000=psr\u0000 com.sun.msv.grammar.AnyN"
+"ameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00007q\u0000~\u0000<sq\u0000~\u00006t\u0000\u001dsimkit.xsd.bindings.P"
+"arametert\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\u0000"
+"\u0003\u00cd\u00dd\u00ffq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0007\u0003\u00cd\u00dd\u00f4ppsq\u0000~\u0000\u0000\u0001\u0095\u00dd}pp\u0000sq\u0000~\u0000\u000f\u0001\u0095\u00ddrppsq\u0000~\u0000\u0011\u0001\u0095\u00ddgq\u0000"
+"~\u0000\u0015psq\u0000~\u0000-\u0001\u0095\u00dddq\u0000~\u0000\u0015pq\u0000~\u0000Iq\u0000~\u0000Kq\u0000~\u0000<sq\u0000~\u00006t\u0000!simkit.xsd.bindi"
+"ngs.ParameterTypeq\u0000~\u0000Nsq\u0000~\u0000\u000f\u00028\u0000rppsq\u0000~\u0000-\u00028\u0000gq\u0000~\u0000\u0015pq\u0000~\u0000/sq\u0000~\u0000"
+"6q\u0000~\u00009q\u0000~\u0000:q\u0000~\u0000<sq\u0000~\u00006t\u0000\tParameterq\u0000~\u0000@q\u0000~\u0000<sq\u0000~\u0000\u000f\u0005\u00cc\u00bf\u000bppsq\u0000~"
+"\u0000\u0011\u0005\u00cc\u00bf\u0000q\u0000~\u0000\u0015psq\u0000~\u0000\u000f\u0005\u00cc\u00be\u00fdq\u0000~\u0000\u0015psq\u0000~\u0000\u0000\u0001\u0095\u00dd}q\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u000f\u0001\u0095\u00ddrppsq\u0000"
+"~\u0000\u0011\u0001\u0095\u00ddgq\u0000~\u0000\u0015psq\u0000~\u0000-\u0001\u0095\u00dddq\u0000~\u0000\u0015pq\u0000~\u0000Iq\u0000~\u0000Kq\u0000~\u0000<sq\u0000~\u00006t\u0000!simkit."
+"xsd.bindings.StateVariableq\u0000~\u0000Nsq\u0000~\u0000\u0000\u00046\u00e1~q\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0007\u00046\u00e1spp"
+"sq\u0000~\u0000\u0000\u0001\u0095\u00dd}pp\u0000sq\u0000~\u0000\u000f\u0001\u0095\u00ddrppsq\u0000~\u0000\u0011\u0001\u0095\u00ddgq\u0000~\u0000\u0015psq\u0000~\u0000-\u0001\u0095\u00dddq\u0000~\u0000\u0015pq\u0000~"
+"\u0000Iq\u0000~\u0000Kq\u0000~\u0000<sq\u0000~\u00006t\u0000%simkit.xsd.bindings.StateVariableTypeq\u0000"
+"~\u0000Nsq\u0000~\u0000\u000f\u0002\u00a1\u0003\u00f1ppsq\u0000~\u0000-\u0002\u00a1\u0003\u00e6q\u0000~\u0000\u0015pq\u0000~\u0000/sq\u0000~\u00006q\u0000~\u00009q\u0000~\u0000:q\u0000~\u0000<sq\u0000"
+"~\u00006t\u0000\rStateVariableq\u0000~\u0000@q\u0000~\u0000<sq\u0000~\u0000\u0011\u0006M\u0018\u00f7ppsq\u0000~\u0000\u000f\u0006M\u0018\u00f4ppsq\u0000~\u0000\u0000\u0001"
+"\u0095\u00dd}pp\u0000sq\u0000~\u0000\u000f\u0001\u0095\u00ddrppsq\u0000~\u0000\u0011\u0001\u0095\u00ddgq\u0000~\u0000\u0015psq\u0000~\u0000-\u0001\u0095\u00dddq\u0000~\u0000\u0015pq\u0000~\u0000Iq\u0000~\u0000K"
+"q\u0000~\u0000<sq\u0000~\u00006t\u0000\u0019simkit.xsd.bindings.Eventq\u0000~\u0000Nsq\u0000~\u0000\u0000\u0004\u00b7;upp\u0000sq\u0000"
+"~\u0000\u0007\u0004\u00b7;jppsq\u0000~\u0000\u0000\u0001\u0095\u00dd}pp\u0000sq\u0000~\u0000\u000f\u0001\u0095\u00ddrppsq\u0000~\u0000\u0011\u0001\u0095\u00ddgq\u0000~\u0000\u0015psq\u0000~\u0000-\u0001\u0095\u00ddd"
+"q\u0000~\u0000\u0015pq\u0000~\u0000Iq\u0000~\u0000Kq\u0000~\u0000<sq\u0000~\u00006t\u0000\u001dsimkit.xsd.bindings.EventTypeq"
+"\u0000~\u0000Nsq\u0000~\u0000\u000f\u0003!]\u00e8ppsq\u0000~\u0000-\u0003!]\u00ddq\u0000~\u0000\u0015pq\u0000~\u0000/sq\u0000~\u00006q\u0000~\u00009q\u0000~\u0000:q\u0000~\u0000<sq"
+"\u0000~\u00006t\u0000\u0005Eventq\u0000~\u0000@sq\u0000~\u0000-\u0002\u009ao\u00acppsq\u0000~\u0000\u0018\u0001\u008a\u008c\u00f2ppsr\u0000%com.sun.msv.dat"
+"atype.xsd.SimpleURType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001dq\u0000~\u0000#t\u0000\ranySimpleType"
+"q\u0000~\u0000\'q\u0000~\u0000)sq\u0000~\u0000*q\u0000~\u0000\u008bq\u0000~\u0000#sq\u0000~\u00006t\u0000\u0007versionq\u0000~\u0000@sq\u0000~\u0000-\u0003x\u00a1~ppq"
+"\u0000~\u0000\u0088sq\u0000~\u00006t\u0000\u0004nameq\u0000~\u0000@sq\u0000~\u0000\u000f\u0002\u00adqBppsq\u0000~\u0000-\u0002\u00adq7q\u0000~\u0000\u0015pq\u0000~\u0000/sq\u0000~\u0000"
+"6q\u0000~\u00009q\u0000~\u0000:q\u0000~\u0000<sq\u0000~\u00006t\u0000\fSimkitModuleq\u0000~\u0000@sr\u0000\"com.sun.msv.gr"
+"ammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/gr"
+"ammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.Ex"
+"pressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006par"
+"entq\u0000~\u0000\u0098[\u0000\u0005tablet\u0000![Lcom/sun/msv/grammar/Expression;xp\u0000\u0000\u0000%\u0000\u0000"
+"\u00009pur\u0000![Lcom.sun.msv.grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfppp"
+"ppppppppppq\u0000~\u0000\tpppppppppppppppppppppppppq\u0000~\u0000,ppppppppppppppp"
+"q\u0000~\u0000\u0092pppppq\u0000~\u0000\u0082q\u0000~\u0000mpppq\u0000~\u0000\u000bq\u0000~\u0000\u0017q\u0000~\u0000Cppq\u0000~\u0000Bpppppppppq\u0000~\u0000\u0013q"
+"\u0000~\u0000Appq\u0000~\u0000\fppppppq\u0000~\u0000\u0010ppppppq\u0000~\u0000Fq\u0000~\u0000Sq\u0000~\u0000aq\u0000~\u0000iq\u0000~\u0000vq\u0000~\u0000~pp"
+"pppq\u0000~\u0000Eq\u0000~\u0000Rq\u0000~\u0000`q\u0000~\u0000hq\u0000~\u0000uq\u0000~\u0000}pppppppppq\u0000~\u0000Pppppq\u0000~\u0000sq\u0000~\u0000"
+"^pq\u0000~\u0000rq\u0000~\u0000]pppq\u0000~\u0000\rpppppq\u0000~\u0000\nq\u0000~\u0000\\ppppppppppppppppppppppppp"
+"ppppppppq\u0000~\u0000\u000epppppppq\u0000~\u0000{q\u0000~\u0000fpq\u0000~\u0000W"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends simkit.xsd.bindings.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(simkit.xsd.bindings.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(simkit.xsd.bindings.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return simkit.xsd.bindings.impl.SimkitModuleImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        attIdx = context.getAttribute("", "version");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        if (("SimkitModule" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  2 :
                        if (("SimkitModule" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  1 :
                        attIdx = context.getAttribute("", "version");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        if (("version" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((simkit.xsd.bindings.impl.SimkitModuleTypeImpl)simkit.xsd.bindings.impl.SimkitModuleImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        attIdx = context.getAttribute("", "version");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  1 :
                            attIdx = context.getAttribute("", "version");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
