package simkit.xml;
/*
 * File:           SimkitHandler.java
 * Date:           February 27, 2004  5:28 PM
 *
 * @author  Rick Goldberg
 * @version generated by NetBeans XML module
 */
import org.xml.sax.*;

public interface SimkitHandler extends ContentHandler { 
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     *
     */
    public void start_Cancel(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     *
     */
    public void end_Cancel() throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes 
     *
     */
    public void handle_Comment(final java.lang.String data, final Attributes meta) throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     *
     */
    public void start_Schedule(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     *
     */
    public void end_Schedule() throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     *
     */
    public void start_State(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     *
     */
    public void end_State() throws SAXException;
    
    /**
     * An empty element event handling method.
     * @param data value or null
     *
     */
    public void handle_StateTransition(final Attributes meta) throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     *
     */
    public void start_Event(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     *
     */
    public void end_Event() throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     *
     */
    public void start_SimkitModule(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     *
     */
    public void end_SimkitModule() throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     *
     */
    public void start_Parameter(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     *
     */
    public void end_Parameter() throws SAXException;
    
}

